# Generated by Django 5.2.5 on 2025-10-09 05:19

import django.core.validators
import django.db.models.deletion
import genesis.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AHJ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('parent_county', models.CharField(max_length=255, null=True)),
                ('state_code', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('website', models.CharField(max_length=255, null=True)),
                ('data_source', models.CharField(max_length=255, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
            ],
            options={
                'db_table': 'ahj',
            },
        ),
        migrations.CreateModel(
            name='ProjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'project_level',
            },
        ),
        migrations.CreateModel(
            name='ReferenceCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reference_codes',
            },
        ),
        migrations.CreateModel(
            name='RequirementBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'requirement_blocks',
            },
        ),
        migrations.CreateModel(
            name='StandardLabels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('always_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'standard_labels',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Plan type (e.g., trial, basic, premium)', max_length=50, unique=True)),
                ('limit', models.PositiveIntegerField(help_text='Usage limit for this plan')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Number of days the plan is valid')),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verticals',
            },
        ),
        migrations.CreateModel(
            name='AHJElectricalRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pv_meter_required', models.BooleanField(default=False)),
                ('pv_meter_required_remarks', models.TextField(blank=True, null=True)),
                ('conductor_sizing_and_ocp', models.TextField(blank=True, help_text='Conductor sizing and overcurrent protection.', null=True)),
                ('is_rsd_needed', models.BooleanField(default=False)),
                ('rsd_requirement', models.TextField(blank=True, help_text='RSD should be next to inverter (AHJ specific requirement).', null=True)),
                ('rsd_requirement_remarks', models.TextField(blank=True, help_text='RSD Requirement remarks.', null=True)),
                ('is_disconnect_required', models.BooleanField(default=False)),
                ('disconnect_remarks', models.TextField(blank=True, help_text='Where disconnect is required (AHJ specific requirement).', null=True)),
                ('is_loading_calculation_required', models.BooleanField(default=False)),
                ('loading_calculation_remarks', models.TextField(blank=True, null=True)),
                ('wire_size_requirements', models.TextField(blank=True, null=True)),
                ('interconnection_type', models.TextField(blank=True, null=True)),
                ('min_conduit_size', models.TextField(blank=True, null=True)),
                ('ess_disconect', models.BooleanField(default=False)),
                ('ess_specific_requirements', models.TextField(blank=True, null=True)),
                ('eld_requirement', models.BooleanField(default=False)),
                ('eld_requirement_remarks', models.BooleanField(default=False)),
                ('grounding_remarks', models.TextField(blank=True, null=True)),
                ('electrical_requirements_notes', models.TextField(blank=True, help_text='Electrical Requirement Notes', null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_electrical_requirement',
            },
        ),
        migrations.CreateModel(
            name='AHJGroundMountRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setback', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum required setback distance in feet', max_digits=6, null=True)),
                ('setback_remarks', models.TextField(blank=True, help_text='Additional notes or remarks about setbacks', null=True)),
                ('location_of_ground_mount', models.CharField(blank=True, help_text='Location description or zoning area for ground mount installation', max_length=255, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_ground_mount_requirement',
            },
        ),
        migrations.CreateModel(
            name='AHJSafetyInstructions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instructions', models.TextField(blank=True, help_text='List of safety instructions for AHJ', null=True)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_instructions', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_safety_instructions',
            },
        ),
        migrations.CreateModel(
            name='AHJSolarRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pv_meter_required', models.BooleanField(default=False)),
                ('ac_disconnect_required', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_solar_requirement',
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'permit_type',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['construction', 'electrical', 'building', 'fire'])), name='permit_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='SolarUtility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('website_link', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('submission_process', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('offset', models.DecimalField(blank=True, decimal_places=2, help_text='Offset percentage (0-100, decimals allowed).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('review_days_part1', models.IntegerField(blank=True, null=True)),
                ('review_days_part2', models.IntegerField(blank=True, null=True)),
                ('application_submission_link_part1', models.TextField(blank=True, null=True)),
                ('application_submission_link_part2', models.TextField(blank=True, null=True)),
                ('requires_combined_pdf', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('project_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projectlevel')),
            ],
            options={
                'db_table': 'solar_utility',
            },
        ),
        migrations.CreateModel(
            name='SolarUtilityPart1Requirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part1_application_form', models.BooleanField(default=False)),
                ('engineering_drawing', models.BooleanField(default=False)),
                ('inverter_datasheet', models.BooleanField(default=False)),
                ('pv_watts', models.BooleanField(default=False)),
                ('change_of_contract_letter', models.BooleanField(default=True)),
                ('docusign_certificate', models.BooleanField(default=True)),
                ('load_calculation_direct', models.BooleanField(default=False)),
                ('load_calculation_pe_stamped', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('solar_utility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part1_requirement', to='app.solarutility')),
            ],
            options={
                'db_table': 'solar_utility_part1_requirement',
            },
        ),
        migrations.CreateModel(
            name='SolarUtilityPart2Requirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificate_of_approval', models.BooleanField(default=False)),
                ('part2_application_form', models.BooleanField(default=False)),
                ('as_built', models.BooleanField(default=False)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('solar_utility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='part2_requirement', to='app.solarutility')),
            ],
            options={
                'db_table': 'solar_utility_part2_requirement',
            },
        ),
        migrations.CreateModel(
            name='StateSpecificInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_specific_ic_code', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_information', to='app.state')),
            ],
            options={
                'db_table': 'state_specific_information',
            },
        ),
        migrations.CreateModel(
            name='AHJRemark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_remark_created', to='app.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_remark_updated', to='app.user')),
            ],
            options={
                'db_table': 'ahj_remarks',
            },
        ),
        migrations.AddField(
            model_name='ahj',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_created', to='app.user'),
        ),
        migrations.AddField(
            model_name='ahj',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_updated', to='app.user'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='app.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.user')),
            ],
            options={
                'db_table': 'user_subscription',
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.CharField(choices=[('city', 'City'), ('township', 'Township'), ('state', 'State'), ('country', 'Country')], max_length=20)),
                ('type', models.CharField(choices=[('gas', 'Gas'), ('solar', 'Solar'), ('sewer', 'Sewer'), ('electric', 'Electric'), ('water', 'Water')], max_length=20)),
                ('website_link', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_created', to='app.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_updated', to='app.user')),
            ],
            options={
                'db_table': 'utility',
            },
        ),
        migrations.AddField(
            model_name='solarutility',
            name='utility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_utilities', to='app.utility'),
        ),
        migrations.CreateModel(
            name='UtilityRemark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_remark_created', to='app.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_remark_updated', to='app.user')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utility')),
            ],
            options={
                'db_table': 'utility_remarks',
            },
        ),
        migrations.CreateModel(
            name='VerticalBlockMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requirement_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_mappings', to='app.requirementblock')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_mappings', to='app.vertical')),
            ],
            options={
                'db_table': 'vertical_block_mapping',
            },
        ),
        migrations.CreateModel(
            name='ZipcodeAHJMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(db_index=True, max_length=20)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
            ],
            options={
                'db_table': 'zipcode_ahj_mapping',
            },
        ),
        migrations.CreateModel(
            name='ZipcodeUtilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(db_index=True, max_length=20)),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utility')),
            ],
            options={
                'db_table': 'zipcode_utility_mapping',
            },
        ),
        migrations.CreateModel(
            name='AHJEnvironmentalData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('exposure_category', models.CharField(blank=True, max_length=10, null=True)),
                ('snow_load', models.FloatField(blank=True, null=True)),
                ('high_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_environmental_data',
                'unique_together': {('ahj',)},
            },
        ),
        migrations.CreateModel(
            name='AHJLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=100)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_label',
                'unique_together': {('ahj', 'label_name')},
            },
        ),
        migrations.CreateModel(
            name='AHJPermits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('construction_permit', models.BooleanField(default=False)),
                ('construction_permit_form', models.CharField(blank=True, help_text='Link to Construction Permit form', max_length=255, null=True)),
                ('electrical_permit', models.BooleanField(default=False)),
                ('electrical_permit_form', models.CharField(blank=True, help_text='Link to Electrical Permit form', max_length=255, null=True)),
                ('building_permit', models.BooleanField(default=False)),
                ('building_permit_form', models.CharField(blank=True, help_text='Link to Building Permit form', max_length=255, null=True)),
                ('fire_permit', models.BooleanField(default=False)),
                ('fire_permit_form', models.CharField(blank=True, help_text='Link to Fire Permit form', max_length=255, null=True)),
                ('zoning', models.BooleanField(default=False)),
                ('zoning_remarks', models.TextField(blank=True, null=True)),
                ('form_of_submission', models.CharField(blank=True, choices=[('hard_copy', 'Hard Copy'), ('online', 'Online')], help_text='Form of submission (Hard copy / Online)', max_length=20, null=True)),
                ('structural_and_electrical_stamp_on_planset', models.BooleanField(default=False)),
                ('seal_type', models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of engineer seal required (Wet or Digital)', max_length=10, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_permits',
                'constraints': [models.CheckConstraint(condition=models.Q(('form_of_submission__in', ['hard_copy', 'online']), ('form_of_submission__isnull', True), _connector='OR'), name='valid_submission_method')],
            },
        ),
        migrations.CreateModel(
            name='AHJRoofMountRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permitted_zones', models.CharField(blank=True, max_length=255, null=True)),
                ('roof_mount_requirements_notes', models.TextField(blank=True, help_text='Notes for Roof Mount Requirement.', null=True)),
                ('maximum_above_roof', models.CharField(blank=True, max_length=255, null=True)),
                ('included_in_building_height', models.BooleanField(default=False)),
                ('roof_boundary_setback', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_shutoff_required', models.BooleanField(default=False)),
                ('shutoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('nec_placard_required', models.BooleanField(default=False)),
                ('placard_location', models.CharField(blank=True, max_length=255, null=True)),
                ('front_yard', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_mount_requirements', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_roof_mount_requirement',
                'unique_together': {('ahj',)},
            },
        ),
        migrations.CreateModel(
            name='AHJStructuralRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('array_layout_required', models.BooleanField(default=False)),
                ('array_layout_required_remarks', models.TextField(blank=True, help_text='Remarks of Aaray Layout.', null=True)),
                ('property_plan_required', models.BooleanField(default=False)),
                ('property_plan_required_remarks', models.TextField(blank=True, help_text='Remarks of Property Plan.', null=True)),
                ('fire_setbacks', models.TextField(blank=True, help_text='Details about Fire Setbacks if any', null=True)),
                ('roof_condition', models.CharField(blank=True, help_text='Condition of the roof (e.g., good, needs repair, unknown)', max_length=255, null=True)),
                ('dead_load_requirement', models.DecimalField(blank=True, decimal_places=2, help_text='Dead load requirement in psf (pounds per square foot)', max_digits=6, null=True)),
                ('max_panel_system_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum panel system weight in pounds per square foot (psf)', max_digits=6, null=True)),
                ('racking_realted_requirement', models.TextField(blank=True, help_text='Details about racking', null=True)),
                ('framing_and_attic_details', models.TextField(blank=True, help_text='Details about Framing & Attic Details', null=True)),
                ('wind_zone_representation_on_planset', models.BooleanField(default=False)),
                ('structural_requirements_notes', models.TextField(blank=True, help_text='Structural Requirement Notes', null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_requirements', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_structural_requirement',
                'unique_together': {('ahj',)},
            },
        ),
        migrations.CreateModel(
            name='AHJPermitMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_mappings', to='app.ahj')),
                ('ahj_permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahj_mappings', to='app.permittype')),
            ],
            options={
                'db_table': 'ahj_permit_mapping',
                'unique_together': {('ahj', 'ahj_permit_type')},
            },
        ),
        migrations.CreateModel(
            name='AHJCodeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_mappings', to='app.ahj')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahj_mappings', to='app.referencecodes')),
            ],
            options={
                'db_table': 'ahj_code_mapping',
                'unique_together': {('ahj', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(help_text='Name of the API called', max_length=100)),
                ('data_id', models.BigIntegerField(blank=True, help_text='Optional resource identifier (e.g., ahj_id, utility_id)', null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage', to='app.user')),
            ],
            options={
                'db_table': 'api_usage',
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_usage_user_id_b7cc9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('expires_at', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_token', to='app.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_token', to='app.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_token', to='app.user')),
            ],
            options={
                'db_table': 'api_token',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='one_active_token_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='ahj',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['city', 'twp', 'state', 'county', 'other'])), name='location_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='one_active_subscription_per_user'),
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['city', 'township', 'state', 'country'])), name='utility_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='utility',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['gas', 'solar', 'sewer', 'electric', 'water'])), name='utility_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='solarutility',
            constraint=models.CheckConstraint(condition=models.Q(('submission_process__in', ['online', 'offline'])), name='solar_submission_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='verticalblockmapping',
            unique_together={('vertical', 'requirement_block')},
        ),
        migrations.AddIndex(
            model_name='zipcodeahjmapping',
            index=models.Index(fields=['zipcode', 'ahj'], name='zipcode_ahj_zipcode_e4b09c_idx'),
        ),
        migrations.AddConstraint(
            model_name='zipcodeahjmapping',
            constraint=models.UniqueConstraint(fields=('zipcode', 'ahj'), name='unique_zipcode_ahj'),
        ),
        migrations.AddIndex(
            model_name='zipcodeutilitymapping',
            index=models.Index(fields=['zipcode', 'utility'], name='zipcode_uti_zipcode_dcc9d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='zipcodeutilitymapping',
            constraint=models.UniqueConstraint(fields=('zipcode', 'utility'), name='unique_zipcode_utility'),
        ),
    ]
