# Generated by Django 5.2.5 on 2025-08-21 05:49

import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.TextField()),
                ('created_on', models.BigIntegerField(default=genesis.utils.current_timestamp)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
