# Generated by Django 5.2.5 on 2025-10-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_init'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ahj',
            name='location_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ahjpermits',
            name='valid_submission_method',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='location_of_ground_mount',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='setback_remarks',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='seal_type',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='structural_and_electrical_stamp_on_planset',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='front_yard',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='included_in_building_height',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='manual_shutoff_required',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='maximum_above_roof',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='nec_placard_required',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='placard_location',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='roof_boundary_setback',
        ),
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='shutoff_location',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='array_layout_required',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='array_layout_required_remarks',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='fire_setbacks',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='property_plan_required',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='property_plan_required_remarks',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='roof_condition',
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='structural_and_electrical_stamp',
            field=models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of engineer seal required (Wet or Digital)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ahjroofmountrequirement',
            name='height_restriction_remarks',
            field=models.TextField(blank=True, help_text='Remarks for height restriction', null=True),
        ),
        migrations.AddField(
            model_name='ahjroofmountrequirement',
            name='restriction_remarks',
            field=models.TextField(blank=True, help_text='Remarks for restriction', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='array_layout_remarks',
            field=models.TextField(blank=True, help_text='Remarks of Aaray Layout.', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='fire_setback_remarks',
            field=models.TextField(blank=True, help_text='Details about Fire Setbacks if any', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='property_plan_remarks',
            field=models.TextField(blank=True, help_text='Remarks of Property Plan.', null=True),
        ),
        migrations.AlterField(
            model_name='ahjgroundmountrequirement',
            name='setback',
            field=models.TextField(blank=True, help_text='Setback Details.', null=True),
        ),
        migrations.AlterField(
            model_name='ahjpermits',
            name='form_of_submission',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], help_text='Form of submission (Hard copy / Online)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ahjroofmountrequirement',
            name='permitted_zones',
            field=models.TextField(blank=True, help_text='Permitted zone details.', null=True),
        ),
        migrations.AddConstraint(
            model_name='ahj',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['city', 'township', 'state', 'county', 'other'])), name='location_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ahjpermits',
            constraint=models.CheckConstraint(condition=models.Q(('form_of_submission__in', ['offline', 'online']), ('form_of_submission__isnull', True), _connector='OR'), name='valid_submission_method'),
        ),
    ]
