# Generated by Django 5.2.5 on 2025-08-21 06:36

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanQuota',
            fields=[
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20, primary_key=True, serialize=False)),
                ('monthly_limit', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'plan_quota',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('token_hash', models.TextField()),
                ('max_calls', models.PositiveIntegerField()),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.user')),
            ],
            options={
                'db_table': 'api_token',
            },
        ),
    ]
