# Generated by Django 5.2.5 on 2025-08-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='StateSpecificInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_specific_ic_code', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_information', to='app.state')),
            ],
            options={
                'db_table': 'state_specific_information',
            },
        ),
    ]
