# Generated by Django 5.2.5 on 2025-10-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_change_in_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjelectricalrequirement',
            old_name='is_rsd_needed',
            new_name='rsd_needed',
        ),
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='rsd_requirement',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='building_permit',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='building_permit_form',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='construction_permit',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='construction_permit_form',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='electrical_permit',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='electrical_permit_form',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='fire_permit',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='fire_permit_form',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='framing_and_attic_details',
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjroofmountrequirement',
            name='framing_and_attic_details',
            field=models.TextField(blank=True, help_text='Details about Framing & Attic Details', null=True),
        ),
    ]
