# Generated by Django 5.2.5 on 2025-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_is_rsd_needed_ahjelectricalrequirement_rsd_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahjpermits',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
