# Generated by Django 5.2.5 on 2025-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscriptionplan_apiusage_apitoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zipcodeahjmapping',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='zipcodeutilitymapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zipcodeahjmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zipcodeutilitymapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='zipcodeahjmapping',
            constraint=models.UniqueConstraint(fields=('zipcode', 'ahj'), name='unique_zipcode_ahj'),
        ),
        migrations.AddConstraint(
            model_name='zipcodeutilitymapping',
            constraint=models.UniqueConstraint(fields=('zipcode', 'utility'), name='unique_zipcode_utility'),
        ),
        migrations.RemoveField(
            model_name='zipcodeahjmapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='zipcodeahjmapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='zipcodeahjmapping',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='zipcodeahjmapping',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='zipcodeutilitymapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='zipcodeutilitymapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='zipcodeutilitymapping',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='zipcodeutilitymapping',
            name='updated_by',
        ),
    ]
