# Generated by Django 5.2.5 on 2025-08-28 13:09

import django.db.models.deletion
import genesis.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_utility_utilitydata_utilityicapplicationrequirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Plan type (e.g., trial, basic, premium)', max_length=50, unique=True)),
                ('limit', models.PositiveIntegerField(help_text='Usage limit for this plan')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Number of days the plan is valid')),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(help_text='Name of the API called', max_length=100)),
                ('data_id', models.BigIntegerField(blank=True, help_text='Optional resource identifier (e.g., ahj_id, utility_id)', null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage', to='app.user')),
            ],
            options={
                'db_table': 'api_usage',
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_usage_user_id_b7cc9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('limit', models.PositiveIntegerField(default=0)),
                ('expires_at', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_token', to='app.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_token', to='app.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_token', to='app.user')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_token', to='app.subscriptionplan')),
            ],
            options={
                'db_table': 'api_token',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='one_active_token_per_user')],
            },
        ),
    ]
