# Generated by Django 5.2.5 on 2025-10-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ahjpermits_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjpermits',
            old_name='zoning_remarks',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='zoning',
        ),
    ]
