# Generated by Django 5.2.5 on 2025-10-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_zoning_remarks_ahjpermits_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahjelectricalrequirement',
            name='eld_requirement_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
