# Generated by Django 5.2.5 on 2025-10-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ahjelectricalrequirement_eld_requirement_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjroofmountrequirement',
            name='height_restriction_remarks',
        ),
    ]
