# Generated by Django 5.2.5 on 2025-09-07 07:29

from django.db import migrations

def populate_project_levels(apps, schema_editor):
    ProjectLevel = apps.get_model("app", "ProjectLevel")
    ProjectLevel.objects.bulk_create([
        ProjectLevel(code="LEVEL_1", name="Level 1", description="<=10KWac"),
        ProjectLevel(code="LEVEL_2", name="Level 2", description=">10KWac"),
        ProjectLevel(code="LEVEL_3", name="Level 3", description=">100KWac and special relaying/metering required"),
    ])



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_projectlevel_solarutility_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_project_levels),
    ]