# Generated by Django 5.2.5 on 2025-10-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ahjroofmountrequirement_height_restriction_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjstructuralrequirement',
            old_name='fire_setback_remarks',
            new_name='setbacks',
        ),
    ]
