# Generated by Django 5.2.5 on 2025-09-07 14:19

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_populate_project_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitoken',
            name='plan',
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expires_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='app.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.user')),
            ],
            options={
                'db_table': 'user_subscription',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='one_active_subscription_per_user')],
            },
        ),
    ]
