# Generated by Django 5.2.5 on 2025-09-24 13:15

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_apitoken_plan_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJRequirementRemark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahjrequirement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_req_remark_created', to='app.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_req_remark_updated', to='app.user')),
            ],
            options={
                'db_table': 'ahj_requirement_remarks',
            },
        ),
    ]
