# Generated by Django 5.2.5 on 2025-10-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_fire_setback_remarks_ahjstructuralrequirement_setbacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjstructuralrequirement',
            old_name='setbacks',
            new_name='fire_setback_remarks',
        ),
    ]
