# Generated by Django 5.2.5 on 2025-09-25 16:16

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_ahj_req_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityRequirementRemark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_remark_created', to='app.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_remark_updated', to='app.user')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utility')),
            ],
            options={
                'db_table': 'utility_requirement_remarks',
            },
        ),
    ]
