# Generated by Django 5.2.5 on 2025-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_setbacks_ahjstructuralrequirement_fire_setback_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjenvironmentaldata',
            name='snow_load',
        ),
        migrations.RemoveField(
            model_name='ahjpermits',
            name='structural_and_electrical_stamp',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='fire_setback_remarks',
        ),
        migrations.AddField(
            model_name='ahj',
            name='structural_and_electrical_stamp',
            field=models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of engineer seal required (Wet or Digital)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ahjenvironmentaldata',
            name='average_high_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjenvironmentaldata',
            name='average_low_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='officer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='officer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='officer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='setback',
            field=models.TextField(blank=True, help_text='Details about Setbacks if any', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='snow_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencecodes',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
