# Generated by Django 5.2.5 on 2025-09-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_utility_req_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
