# Generated by Django 5.2.5 on 2025-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_ahjenvironmentaldata_snow_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahj',
            name='generic_forms_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
