# Generated by Django 5.2.5 on 2025-09-30 11:13

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_unique_state_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UtilityRequirementRemark',
            new_name='UtilityRemark',
        ),
        migrations.AlterModelTable(
            name='utilityremark',
            table='utility_remarks',
        ),
        migrations.CreateModel(
            name='AHJRemark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_remark_created', to='app.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahj_remark_updated', to='app.user')),
            ],
            options={
                'db_table': 'ahj_remarks',
            },
        ),
        migrations.DeleteModel(
            name='AHJRequirementRemark',
        ),
    ]
