# Generated by Django 5.2.5 on 2025-10-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_field_generic_forms_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjpermits',
            name='remarks',
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='remarks1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
