# Generated by Django 5.2.5 on 2025-10-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_ahjpermits_remarks_ahjpermits_remarks1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjpermits',
            name='remarks1',
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
