# Generated by Django 5.2.5 on 2025-10-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_update_ahj_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'requirement_blocks',
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'verticals',
            },
        ),
        migrations.CreateModel(
            name='VerticalBlockMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requirement_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_mappings', to='app.requirementblock')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_mappings', to='app.vertical')),
            ],
            options={
                'db_table': 'vertical_block_mapping',
                'unique_together': {('vertical', 'requirement_block')},
            },
        ),
    ]
