# Generated by Django 5.2.5 on 2025-11-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_ahjpermits_remarks1_ahjpermits_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjpermits',
            name='fees',
        ),
        migrations.AddField(
            model_name='ahj',
            name='parent_county_website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
