# Generated by Django 5.2.5 on 2025-10-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_verticals'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardLabels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('always_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'standard_labels',
            },
        ),
        migrations.CreateModel(
            name='AHJSafetyInstructions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('equipment_location_remarks', models.TextField(blank=True, null=True)),
                ('roof_load_remarks', models.TextField(blank=True, null=True)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_instructions', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_safety_instructions',
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'permit_type',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['construction', 'electrical', 'building', 'fire'])), name='permit_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('code_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reference_codes',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['building', 'electrical', 'fire', 'safety'])), name='reference_codes_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='AHJLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=100)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_label',
                'unique_together': {('ahj', 'label_name')},
            },
        ),
        migrations.CreateModel(
            name='AHJPermitMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_mappings', to='app.ahj')),
                ('ahj_permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahj_mappings', to='app.permittype')),
            ],
            options={
                'db_table': 'ahj_permit_mapping',
                'unique_together': {('ahj', 'ahj_permit_type')},
            },
        ),
        migrations.CreateModel(
            name='AhjCodeMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_mappings', to='app.ahj')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahj_mappings', to='app.referencecodes')),
            ],
            options={
                'db_table': 'ahj_code_mapping',
                'unique_together': {('ahj', 'code')},
            },
        ),
    ]
