# Generated by Django 5.2.5 on 2025-10-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_reference_codes_permits_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AHJSpecificRequirement',
        ),
    ]
