# Generated by Django 5.2.5 on 2025-11-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_ahjpermits_fees_ahj_parent_county_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('building', 'Building Subcode'), ('fire', 'Fire Subcode'), ('electric', 'Electric Subcode'), ('plumbing', 'Plumbing Subcode'), ('mechanical', 'Mechanical Subcode'), ('certificate', 'Certificate & Other Fees'), ('other', 'Other')], help_text='Type of subcode this fee belongs to', max_length=50)),
                ('item', models.CharField(help_text='Description of the item or fee purpose', max_length=255)),
                ('fee', models.CharField(help_text="Fee value or rule, e.g. '$75', '$30 per $1,000 cost', '0.045 per cubic foot'", max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('code_section', models.CharField(blank=True, default='§64-3', max_length=50, null=True)),
                ('township', models.CharField(default='Alexandria, NJ', max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('retrieved_on', models.DateField(blank=True, null=True)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='app.ahj')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'ordering': ['type', 'id'],
            },
        ),
    ]
