# Generated by Django 5.2.5 on 2025-10-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_ahj_specific_requirements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AHJRequirement',
            new_name='AHJSolarRequirement',
        ),
        migrations.AlterModelTable(
            name='ahjsolarrequirement',
            table='ahj_solar_requirement',
        ),
    ]
