# Generated by Django 5.2.5 on 2025-10-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_refactor_ahj_requirements_to_solar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJEnvironmentalData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('exposure_category', models.CharField(blank=True, max_length=10, null=True)),
                ('snow_load', models.FloatField(blank=True, null=True)),
                ('high_temp', models.FloatField(blank=True, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_environmental_data',
                'unique_together': {('ahj',)},
            },
        ),
    ]
