# Generated by Django 5.2.5 on 2025-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_add_ahj_environmental_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='ahj_specific_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='certified_electrical_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='conductor_sizing_and_ocp',
            field=models.TextField(blank=True, help_text='Conductor sizing and overcurrent protection.', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='conduit_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='conduit_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='datasheets',
            field=models.URLField(blank=True, help_text='Link to datasheet.', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='disconnect_requirement',
            field=models.TextField(blank=True, help_text='Where disconnect is required (AHJ specific requirement).', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='e_stop_button_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='electrical_panel_connection',
            field=models.TextField(blank=True, help_text='Electrical panel connection (The 120% Rule).', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='electrical_stamping',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='ess_specific_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='grounding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='grounding_and_bonding_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='grounding_electrode_conductor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='interconnection_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='is_disconnect_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='is_grounding_and_bonding_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='is_loading_calculation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='is_rsd_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='junction_box',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='labeling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='loading_calculation_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='main_service_panel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='one_line_requirement',
            field=models.CharField(blank=True, help_text='One line / three line requirement for residential or commercial property.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='placard_requirement_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='power_line_filter_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='production_meter_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='recommended_ic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='rsd_requirement',
            field=models.TextField(blank=True, help_text='RSD should be next to inverter (AHJ specific requirement).', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='rule_120_percent_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='service_panel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='spd_device',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='string_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='three_line_diagram_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='three_line_diagram_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='utility_meter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='utility_specific_note_of_eld',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='wire_size_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
