# Generated by Django 5.2.5 on 2025-10-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_add_feilds_ahj_electrical_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjelectricalrequirement',
            old_name='disconnect_requirement',
            new_name='disconnect_remarks',
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='ac_disconnect_type_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='ee_stamp_for_main_breaker_derate_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='pv_meter_required_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralsetbackrequirement',
            name='seal_type',
            field=models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of seal required (Wet or Digital)', max_length=10, null=True),
        ),
    ]
