# Generated by Django 5.2.5 on 2025-10-03 11:23

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_add_remark_feilds_ahj_electrical_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahjstructuralsetbackrequirement',
            name='stamp_required',
            field=models.BooleanField(default=True, editable=False, help_text='Does structural work require an engineer stamp?'),
        ),
        migrations.CreateModel(
            name='AHJStructuralRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flat_roof', models.BooleanField(default=False, help_text='Is the roof flat?')),
                ('roof_condition', models.CharField(blank=True, help_text='Condition of the roof (e.g., good, needs repair, unknown)', max_length=255, null=True)),
                ('structural_stamp_by_contractor', models.BooleanField(default=False, help_text='Is a structural stamp required by a certified contractor?')),
                ('dead_load_requirement', models.DecimalField(blank=True, decimal_places=2, help_text='Dead load requirement in psf (pounds per square foot)', max_digits=6, null=True)),
                ('property_lines', models.TextField(blank=True, help_text='Details about property lines relevant to structural requirements', null=True)),
                ('obstructions', models.TextField(blank=True, help_text='Notes on obstructions affecting structural requirements', null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_requirements', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_structural_requirement_data',
                'unique_together': {('ahj',)},
            },
        ),
    ]
