# Generated by Django 5.2.5 on 2025-10-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_ahj_structural_requirements'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ahjstructuralrequirement',
            table='ahj_structural_requirement',
        ),
    ]
