# Generated by Django 5.2.5 on 2025-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_name_change_ahj_structural_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='datasheets',
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='data_sheets',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
