# Generated by Django 5.2.5 on 2025-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_fixed_data_sheets_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahj',
            name='data_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahj',
            name='parent_county',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahj',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
