# Generated by Django 5.2.5 on 2025-10-03 13:35

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_new_ahj_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJRoofMountRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permitted_zones', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_above_roof', models.CharField(blank=True, max_length=255, null=True)),
                ('included_in_building_height', models.BooleanField(default=False)),
                ('roof_boundary_setback', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_shutoff_required', models.BooleanField(default=False)),
                ('shutoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('nec_placard_required', models.BooleanField(default=False)),
                ('placard_location', models.CharField(blank=True, max_length=255, null=True)),
                ('front_yard', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_mount_requirements', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_roof_mount_requirement',
                'unique_together': {('ahj',)},
            },
        ),
    ]
