# Generated by Django 5.2.5 on 2025-10-03 14:22

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_add_roof_mount_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJSolarFireRequirements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fire_access', models.BooleanField(default=False, help_text='Is fire access required?')),
                ('other_ahj_specific_req', models.TextField(blank=True, help_text='Other AHJ-specific fire-related requirements', null=True)),
                ('evacuation_plan', models.BooleanField(default=False, help_text='Is evacuation plan required?')),
                ('rapid_shutdown_information', models.BooleanField(default=False, help_text='Is rapid shutdown information required?')),
                ('fire_code_setbacks', models.BooleanField(default=False, help_text='Are fire code setbacks required?')),
                ('location_of_disconnects', models.BooleanField(default=False, help_text='Location of disconnects required?')),
                ('fire_resistant_materials', models.BooleanField(default=False, help_text='Fire-resistant materials compliance required?')),
                ('battery_storage_compliance', models.BooleanField(default=False, help_text='Battery storage systems compliance required?')),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_fire_requirement', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_solar_fire_requirement',
                'unique_together': {('ahj',)},
            },
        ),
    ]
