# Generated by Django 5.2.5 on 2025-10-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_add_ahj_solar_fire_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='freeze_depth',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='setback_back',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='setback_front',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='setback_side',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='soil_class',
        ),
        migrations.RemoveField(
            model_name='ahjgroundmountrequirement',
            name='thaw_depth',
        ),
        migrations.AddField(
            model_name='ahjgroundmountrequirement',
            name='location_of_ground_mount',
            field=models.CharField(blank=True, help_text='Location description or zoning area for ground mount installation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjgroundmountrequirement',
            name='setback',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum required setback distance in feet', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ahjgroundmountrequirement',
            name='setback_remarks',
            field=models.TextField(blank=True, help_text='Additional notes or remarks about setbacks', null=True),
        ),
    ]
