# Generated by Django 5.2.5 on 2025-10-06 11:30

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_ahjgroundmountrequirement_soil_class_type_valid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJSetbackRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stamp_required', models.BooleanField(default=True, editable=False, help_text='Does structural work require an engineer stamp?')),
                ('seal_type', models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of seal required (Wet or Digital)', max_length=10, null=True)),
                ('fire_setback_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Fire setback in feet (if specified)', max_digits=6, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_setback_requirement',
            },
        ),
    ]
