# Generated by Django 5.2.5 on 2025-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_ahjsetbackrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjsetbackrequirement',
            name='seal_type',
        ),
        migrations.RemoveField(
            model_name='ahjsetbackrequirement',
            name='stamp_required',
        ),
        migrations.AddField(
            model_name='ahjsetbackrequirement',
            name='fire_setback_distance_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='seal_type',
            field=models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of seal required (Wet or Digital)', max_length=10, null=True),
        ),
    ]
