# Generated by Django 5.2.5 on 2025-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_ahjsetbackrequirement_seal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjstructuralsetbackrequirement',
            name='ahj',
        ),
        migrations.RemoveConstraint(
            model_name='ahjelectricalrequirement',
            name='ac_disconnect_type_valid',
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='busbar_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Main service panel busbar rating in amperes', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='conductor_material',
            field=models.TextField(blank=True, help_text='Conductor material.', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='electrical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='ess_disconect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='production_meter_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ahjelectricalrequirement',
            name='ac_disconnect_type',
            field=models.CharField(blank=True, help_text='fused / non-fused', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ahjelectricalrequirement',
            name='data_sheets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='ahjelectricalrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('ac_disconnect_type__in', ['fused', 'non-fused']), ('ac_disconnect_type__isnull', True), _connector='OR'), name='ac_disconnect_type_valid'),
        ),
        migrations.DeleteModel(
            name='AHJStructuralSetbackRequirement',
        ),
    ]
