# Generated by Django 5.2.5 on 2025-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_ahjstructuralsetbackrequirement_ahj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahj',
            name='building_code',
        ),
        migrations.RemoveField(
            model_name='ahj',
            name='nec_code',
        ),
        migrations.RemoveField(
            model_name='ahj',
            name='nfpa_code',
        ),
        migrations.AddField(
            model_name='referencecodes',
            name='building_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referencecodes',
            name='nec_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referencecodes',
            name='nfpa_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
