# Generated by Django 5.2.5 on 2025-10-06 13:59

import django.db.models.deletion
import genesis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_add_fields_in_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHJPermits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('construction_form', models.BooleanField(default=False)),
                ('construction_form_remarks', models.TextField(blank=True, null=True)),
                ('electrical_form', models.BooleanField(default=False)),
                ('electrical_form_remarks', models.TextField(blank=True, null=True)),
                ('building_form', models.BooleanField(default=False)),
                ('building_form_remarks', models.TextField(blank=True, null=True)),
                ('fire_form', models.BooleanField(default=False)),
                ('fire_form_remarks', models.TextField(blank=True, null=True)),
                ('zoning', models.CharField(blank=True, choices=[('ground_mount', 'Ground Mount'), ('roof_mount', 'Roof Mount')], help_text='Applicable zoning type (Ground mount or Roof mount)', max_length=50, null=True)),
                ('structural_stamp_on_planset', models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of structural stamp on planset (Wet/Digital)', max_length=10, null=True)),
                ('electrical_stamp_on_planset', models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of electrical stamp on planset (Wet/Digital)', max_length=10, null=True)),
                ('form_of_submission', models.CharField(blank=True, choices=[('hard_copy', 'Hard Copy'), ('online', 'Online')], help_text='Form of submission (Hard copy / Online)', max_length=20, null=True)),
                ('created_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('updated_at', models.BigIntegerField(default=genesis.utils.current_timestamp)),
                ('ahj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='app.ahj')),
            ],
            options={
                'db_table': 'ahj_permits',
                'constraints': [models.CheckConstraint(condition=models.Q(('zoning__in', ['ground_mount', 'roof_mount']), ('zoning__isnull', True), _connector='OR'), name='valid_zoning_type'), models.CheckConstraint(condition=models.Q(('structural_stamp_on_planset__in', ['wet', 'digital']), ('structural_stamp_on_planset__isnull', True), _connector='OR'), name='valid_structural_stamp'), models.CheckConstraint(condition=models.Q(('electrical_stamp_on_planset__in', ['wet', 'digital']), ('electrical_stamp_on_planset__isnull', True), _connector='OR'), name='valid_electrical_stamp'), models.CheckConstraint(condition=models.Q(('form_of_submission__in', ['hard_copy', 'online']), ('form_of_submission__isnull', True), _connector='OR'), name='valid_submission_method')],
            },
        ),
    ]
