# Generated by Django 5.2.5 on 2025-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_ahjpermits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='loading_calculation_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Threshold load that requires structural calculations (in psf)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='max_panel_system_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum panel system weight in pounds per square foot (psf)', max_digits=6, null=True),
        ),
    ]
