# Generated by Django 5.2.5 on 2025-10-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_ahjstructuralrequirement_loading_calculation_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='array_layout',
            field=models.TextField(blank=True, help_text='Details about array layout', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='attic_remarks',
            field=models.TextField(blank=True, help_text='Details about Attic', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='fire_setbacks',
            field=models.TextField(blank=True, help_text='Details about Fire Setbacks if any', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='framing_details',
            field=models.TextField(blank=True, help_text='Details about Framing Details', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='property_plan',
            field=models.TextField(blank=True, help_text='Details about property plan', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='racking',
            field=models.TextField(blank=True, help_text='Details about racking', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='wind_zone_shown_on_planset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='wind_zone_shown_on_planset_remarks',
            field=models.TextField(blank=True, help_text='Details about Wind zone on the planset', null=True),
        ),
    ]
