# Generated by Django 5.2.5 on 2025-10-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_field_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencecodes',
            name='building_code',
        ),
        migrations.RemoveField(
            model_name='referencecodes',
            name='nec_code',
        ),
        migrations.RemoveField(
            model_name='referencecodes',
            name='nfpa_code',
        ),
    ]
