# Generated by Django 5.2.5 on 2025-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_reference_codes_table_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ahjpermits',
            old_name='building_form',
            new_name='building_permit',
        ),
        migrations.RenameField(
            model_name='ahjpermits',
            old_name='construction_form',
            new_name='construction_permit',
        ),
        migrations.RenameField(
            model_name='ahjpermits',
            old_name='electrical_form',
            new_name='electrical_permit',
        ),
        migrations.RenameField(
            model_name='ahjpermits',
            old_name='fire_form',
            new_name='fire_permit',
        ),
        migrations.RenameField(
            model_name='referencecodes',
            old_name='code_name',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='conductor_material',
        ),
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='conduit_type',
        ),
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='labeling',
        ),
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='main_service_panel',
        ),
        migrations.RemoveField(
            model_name='ahjelectricalrequirement',
            name='spd_device',
        ),
        migrations.RemoveField(
            model_name='ahjsafetyinstructions',
            name='equipment_location_remarks',
        ),
        migrations.RemoveField(
            model_name='ahjsafetyinstructions',
            name='roof_load_remarks',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='obstructions',
        ),
        migrations.RemoveField(
            model_name='ahjstructuralrequirement',
            name='seal_type',
        ),
        migrations.RemoveField(
            model_name='referencecodes',
            name='type',
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='electrical_requirements_notes',
            field=models.TextField(blank=True, help_text='Electrical Requirement Notes', null=True),
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='rsd_requirement_remarks',
            field=models.TextField(blank=True, help_text='RSD Requirement remarks.', null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='building_permit_form',
            field=models.CharField(blank=True, help_text='Link to Building Permit form', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='construction_permit_form',
            field=models.CharField(blank=True, help_text='Link to Construction Permit form', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='electrical_permit_form',
            field=models.CharField(blank=True, help_text='Link to Electrical Permit form', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='fire_permit_form',
            field=models.CharField(blank=True, help_text='Link to Fire Permit form', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ahjroofmountrequirement',
            name='roof_mount_requirements_notes',
            field=models.TextField(blank=True, help_text='Notes for Roof Mount Requirement.', null=True),
        ),
        migrations.AddField(
            model_name='ahjsafetyinstructions',
            name='instructions',
            field=models.TextField(blank=True, default=list, help_text='List of safety instructions for AHJ'),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='array_layout_required_remarks',
            field=models.TextField(blank=True, help_text='Remarks of Aaray Layout.', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='property_plan_required_remarks',
            field=models.TextField(blank=True, help_text='Remarks of Property Plan.', null=True),
        ),
        migrations.AddField(
            model_name='ahjstructuralrequirement',
            name='structural_requirements_notes',
            field=models.TextField(blank=True, help_text='Structural Requirement Notes', null=True),
        ),
        migrations.AlterField(
            model_name='ahjpermits',
            name='structural_and_electrical_stamp_on_planset',
            field=models.CharField(blank=True, help_text='Type of stamp on planset (Wet / Digital / Required)', max_length=20, null=True),
        ),
    ]
