# Generated by Django 5.2.5 on 2025-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_change_in_ahj_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahjsafetyinstructions',
            name='instructions',
            field=models.TextField(blank=True, help_text='List of safety instructions for AHJ', null=True),
        ),
    ]
