# Generated by Django 5.2.5 on 2025-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_change_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjpermits',
            name='zoning',
        ),
        migrations.AddField(
            model_name='ahjelectricalrequirement',
            name='grounding_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='zoning_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='zonings',
            field=models.BooleanField(default=False),
        ),
    ]
