# Generated by Django 5.2.5 on 2025-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_change_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahjpermits',
            name='zonings',
        ),
        migrations.AddField(
            model_name='ahjpermits',
            name='zoning',
            field=models.BooleanField(default=False),
        ),
    ]
