# Generated by Django 5.2.5 on 2025-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_zoning_field_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahjpermits',
            name='structural_and_electrical_stamp_on_planset',
            field=models.BooleanField(default=False),
        ),
    ]
