# Generated by Django 5.2.5 on 2025-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_change_structural_and_electrical_stamp_on_planset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahjpermits',
            name='seal_type',
            field=models.CharField(blank=True, choices=[('wet', 'Wet'), ('digital', 'Digital')], help_text='Type of engineer seal required (Wet or Digital)', max_length=10, null=True),
        ),
    ]
