# Generated by Django 5.2.5 on 2025-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_add_seal_type_in_permits'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ahjelectricalrequirement',
            name='ac_disconnect_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='ahjpermits',
            name='valid_zoning_type',
        ),
        migrations.RemoveConstraint(
            model_name='ahjpermits',
            name='valid_structural_stamp',
        ),
        migrations.RemoveConstraint(
            model_name='ahjpermits',
            name='valid_electrical_stamp',
        ),
        migrations.RemoveConstraint(
            model_name='referencecodes',
            name='reference_codes_type_valid',
        ),
        migrations.AddConstraint(
            model_name='ahj',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['city', 'twp', 'state', 'county', 'other'])), name='location_type_valid'),
        ),
    ]
